# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('profilepic', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('backgroundimage', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('bio', models.TextField()),
                ('email', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
